### ISSUE TITLE
Remove old Snyk reports for forge/tig from the snyk dashboard

### ISSUE THREAD

**Issue by jonathansmolenski** [podaac/forge#26]
The snyk reports that were coming from the command line on Jenkins are still scanning and need to be moved to the new github repos instead

**Comment by jamesfwood** [comment]
Also check the other repos too.  There may be more than forge and tig.  Thanks!
And remove any obsolete ones as well.

**Comment by jonathansmolenski** [comment]
I've removed both the Tig and the Forge results from the command line snyk results.  I've also disabled the jenkins job here: for the tig-test repo which exists on the old github server, so those results won't appear in the snyk reports either.
