### ISSUE TITLE
SCATSAT1_ESDR_L2_WIND_STRESS_V1.1:  Failing to create footprint

### ISSUE THREAD

**Issue by jamesfwood** [podaac/forge#32]

**Comment by DeanHenze** [comment]
![Uploading footprint_coverage_example_SCATSAT1_ESDR_L2_WIND_STRESS_V1.1.png…]()

**Comment by DeanHenze** [comment]
![footprint_coverage_example_SCATSAT1_ESDR_L2_WIND_STRESS_V1 1](https://github.com/podaac/forge/assets/54649692/415c44dd-cb2a-4818-8ae5-b3299fe907b4)

**Comment by jamesfwood** [comment]
Will move this to the new pyforge
